### ISSUE TITLE
Need null safety support

### ISSUE THREAD

**Issue by Basher7** [engapplabs/flutter_websocket_plugin#17]
**from flutter v2.0.2, flutter is now null-safety mechanism. Most of the packages already upgrade to null safety and more are upgrading.**

Thanks for this great package!

_Do you plan to make a null safe version of the package?_

**Comment by Syaba999** [comment]
You can use my fork
```
websocket_manager:
  git:
    url: git://github.com/Syaba999/flutter_websocket_plugin
    ref: nullsafety
```
